booking/urls.py
from . import views
from django.urls import path
from booking.views import\
    create_reservation, update_reservation, remove_reservation

app_name = 'booking'

urlpatterns = [
    path('', views.home, name='home'),
    path('bookings/', views.ReservationList.as_view(), name='bookings'),
    path('create_reservations/', views.create_reservation,
         name='create_reservations'),
    path('update_reservation/<int:reservation_id>', views.update_reservation,
         name='update_reservation'),
    path('remove_reservation/<int:reservation_id>/', views.remove_reservation,
         name='remove_reservation'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
    path('accounts/', include('allauth.urls')),
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.core.exceptions import ValidationError
from django.utils import timezone


TIMES_AVAILABLE = [
    ('time1', "17:00"),
    ('time2', "17:15"),
    ('time3', "17:30"),
    ('time4', "17:45"),
    ('time5', "18:00"),
    ('time6', "18:15"),
    ('time7', "18:30"),
    ('time8', "18:45"),
    ('time9', "19:00"),
    ('time10', "19:15"),
    ('time11', "19:30"),
    ('time12', "19:45"),
    ('time13', "20:00"),
    ('time14', "20:15"),
    ('time15', "20:30"),
    ('time16', "20:45"),
]

PARTY_SIZE = [
    ('p_num1', '1'),
    ('p_num2', '2'),
    ('p_num3', '3'),
    ('p_num4', '4'),
    ('p_num5', '5'),
    ('p_num6', '6'),
    ('p_num7', '7'),
    ('p_num8', '8'),
    ('p_num9', '9'),
    ('p_num10', '10'),
]


def validate_future_date(value):
    if value < timezone.now().date():
        raise ValidationError('Date cannot be in the past')


class Reservation(models.Model):
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    day = models.DateField(validators=[validate_future_date])
    time = models.CharField(choices=TIMES_AVAILABLE, max_length=10)
    party_size = models.CharField(choices=PARTY_SIZE, max_length=10)

    def __str__(self):
        return self.name

booking/forms.py
from .models import Reservation
from django.forms.widgets import NumberInput
from django import forms
from .models import PARTY_SIZE, TIMES_AVAILABLE
from django.forms import ModelForm


class ReservationForm(ModelForm):
    """
    Reservation Form
    """
    name = forms.CharField(label='Enter Name ', required=True, max_length=25)

    day = forms.DateField(widget=NumberInput(attrs={'type': 'date'}))

    time = forms.ChoiceField(choices=TIMES_AVAILABLE)

    party_size = forms.ChoiceField(choices=PARTY_SIZE)

    class Meta:
        model = Reservation
        fields = ('name', 'day', 'time', 'party_size')

booking/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import views
from django.views import generic, View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .models import Reservation
from .forms import ReservationForm


# View the Home Page #
def home(request):
    return render(request, 'index.html')


# View Reservations #
class ReservationList(LoginRequiredMixin, generic.ListView):
    model = Reservation
    template_name = 'bookings.html'
    queryset = Reservation.objects.all()
    paginate_by = 5

    def get_queryset(self):
        return Reservation.objects.filter(user=self.request.user)


# Create Reservation #
@login_required
def create_reservation(request):
    """
    User can create a reservation
    """
    if request.method == 'POST':
        reservation_form = ReservationForm(request.POST)
        if reservation_form.is_valid():
            reservation = reservation_form.save(commit=False)
            reservation.user = request.user
            reservation.approved = False
            reservation.save()
            messages.success(request, 'Your reservation was successful.')
            return redirect('booking:bookings')
        else:
            messages.error(request, 'There is an error with your reservation.\
                    Please check all fields, amend and try again.')
    else:
        reservation_form = ReservationForm()
    context = {
        'form': reservation_form
    }
    return render(request, 'create_reservation.html', context)


# Update Reservation #
@login_required
def update_reservation(request, reservation_id):
    """
    User can amend a reservation
    """
    booking = get_object_or_404(Reservation, id=reservation_id)
    if request.method == 'POST':
        reservation_form = ReservationForm(request.POST)
        if reservation_form.is_valid():
            messages.success(request,
                             'Your reservation was successfully updated.')
            return redirect('booking:bookings')
        else:
            messages.error(request,
                           'Reservation wasnt updated successfully.\
                           Please amend and try again.')
            reservation_form = ReservationForm()
            context = {
                'form': reservation_form
            }
    else:
        reservation_form = ReservationForm()
    context = {
        'form': reservation_form
    }
    return render(request, 'update_reservation.html', context)


# Delete Reservation #
@login_required
def remove_reservation(request, reservation_id):
    """
    User can delete a reservation
    """
    booking = get_object_or_404(Reservation, id=reservation_id)
    booking.delete()
    messages.success(request,
                     'Your reservation has been sucessfully deleted')
    return redirect('booking:bookings')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Galaxy Gourment. Eatery and Bar.">
    <meta name="keywords" content="food, bar, desserts, drinks">
    <!--Bootstrap CDN-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Oswald&family=Playpen+Sans:wght@600&family=Skranji:wght@700&family=Titillium+Web:wght@300&display=swap" rel="stylesheet">
    {% load static %}
    <!--CSS-->   
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--FontAwesome-->
    <script src="https://kit.fontawesome.com/1bb1a905c4.js" crossorigin="anonymous"></script>
    <!--Favicon-->
    <link href="https://res.cloudinary.com/dmtng0i7p/image/upload/v1698705929/PP4_Restaurant/favicon_txpiqb.ico" rel="icon" type="image/x-icon">
    <title>{% block title %} Galaxy Gourment {% endblock %}</title>    
</head>

  <body class="d-flex flex-column h-100 main-bg">
    <header>
        <div class="header">
        <a href="{% url 'booking:home'%}"><span class="red-word">Galaxy</span><span class="purple-word">Gourmet</span></a>
        </div>

    <!--Navigation-->
        <nav>
            <div>
                <ul class="navbar">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="btn btn-primary" href="{% url 'booking:create_reservations' %}" role="button">Book</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-info" href="{% url 'booking:bookings' %}" role="button">Your Details</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-danger" href="{% url 'account_logout' %}" role="button">SignOut</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="btn btn-primary" href="{% url 'account_signup' %}">Account Register</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-info" href="{% url 'account_login' %}">SignIn</a>
                </li>
                {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <main>
    {% block content %}
    
    {% endblock content %}    
    </main>    

    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 2500);
    </script>    
  </body>

</html>

templates/bookings.html
{% extends 'base.html' %} {% block content %}
<div class="row g-5">    
  {% for reservation in reservation_list %}
  <div class="col-md-6 offset-md-3 col-sm-3">
    <div class="card border border-info justify-content-center h-100">
      <div class="card-body">
        <h4 class="text-center"><strong>Reservation Name:</strong> {{ reservation.name }}</h4>
        <div class="card-text">
          <div class="text-center">
            <p class="mb-2"><strong>Day:</strong> {{ reservation.day }}</p>
            <p class="mb-2"><strong>Time:</strong> {{ reservation.get_time_display }}</p>
            <p class="mb-2"><strong>Party Size:</strong> {{ reservation.get_party_size_display }}
            </p>
          </div>
          <a href="{% url 'booking:update_reservation' reservation.id %}" class="btn btn-success">Update</a>
          <a href="{% url 'booking:remove_reservation' reservation.id  %}" class="btn btn-danger">Delete</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

<style>
  body {
    background-image: url('https://res.cloudinary.com/dmtng0i7p/image/upload/c_scale,h_1218,w_2001/v1709828026/PP4_Restaurant/pexels-geraud-pfeiffer-6542790_fmzmrw.jpg');
  }
  </style>
</div>
{% endblock content %} 

templates/create_reservation.html
{% extends 'base.html' %} 
{% block content %}

<div class="container">
    <div class="card-content">
        <h2 class="mx-auto" style="width: 300px">Reservation Details</h2>
    </div>
</div>
<br>

<div class="container">
  <div class="row">
    <div class="col-s12-m4">
      <div class="card">        
          <form method="post" action="">
            {% csrf_token %} {{ form.as_p }}
            <input type="submit" value="Book" class="btn btn-success submit-button">
          </form>        
      </div>
    </div>
  </div>
</div>
<style>
  body {
    background-image: url('https://res.cloudinary.com/dmtng0i7p/image/upload/c_scale,w_2189/v1709829212/PP4_Restaurant/pexels-engin-akyurt-1437267_ye8qlc.jpg');
  }
</style>
{% endblock content %}

templates/index.html
{% extends 'base.html' %} 
{% block content %}

<div class="header">      
    <div class="text-body">
        <h3>Welcome to <strong>Galaxy Gourment</strong></h3>
        <p>Food that is <strong>OUT OF THIS WORLD!</strong></p>                
        <p>Our menu, aswell as our reservation times, are below.</p>
    </div>
</div>

<br>

<div class="card">
    <div class="card-body">
        <h4 class="mx-auto" style="width: 200px"><strong>Menu</strong></h4>
    </div>
</div>

<br>

<div class="container">
    <div class="starter">       
        <h3 class="mx-auto" style="width: 200px"><strong>Starter</strong></h3>
        <div class="mx-auto" style="width: 150px"><p>Garlic Bread</p></div>
        <div class="mx-auto" style="width: 150px"><p>Nachos</p></div>
        <div class="mx-auto" style="width: 150px"><p>Soup of the Day</p></div>        
    </div>
    <div class="mains">        
        <h3 class="mx-auto" style="width: 200px"><strong>Mains</strong></h3>
        <div class="mx-auto" style="width: 150px"><p>Cheese Burger</p></div>
        <div class="mx-auto" style="width: 150px"><p>Steak</p></div>
        <div class="mx-auto" style="width: 150px"><p>Meat and Potato Pie</p></div>
    </div>
    <div class="sides">        
        <h3 class="mx-auto" style="width: 200px"><strong>Sides</strong></h3>
        <div class="mx-auto" style="width: 150px"><p>Chips</p></div>
        <div class="mx-auto" style="width: 150px"><p>Wedges</p></div>
        <div class="mx-auto" style="width: 150px"><p>Curly Chips</p></div>  
    </div>
    <div class="desserts">      
        <h3 class="mx-auto" style="width: 200px"><strong>Dessert</strong></h3>
        <div class="mx-auto" style="width: 150px"><p>Apple Pie</p></div>
        <div class="mx-auto" style="width: 150px"><p>Strawberry Pudding and Custard</p></div>
        <div class="mx-auto" style="width: 150px"><p>Ice Cream</p></div>   
    </div>
    <div class="drinks">        
        <h3 class="mx-auto" style="width: 200px"><strong>Drinks</strong></h3>
        <div class="mx-auto" style="width: 150px"><p>Beer</p></div>
        <div class="mx-auto" style="width: 150px"><p>Wine</p></div>
        <div class="mx-auto" style="width: 150px"><p>Pepsi</p></div>
        <div class="mx-auto" style="width: 150px"><p>Orange Juice</p></div>
    </div>
</div>

<br>

<div class="times">
   <h3 class="mx-auto" style="width: 200px">Times</h3>
    <div class="container">
        <div class="col s12">
            <div class="row">
                <span class="border border-dark col s1">17:00</span>
                <span class="border border-dark col s1">17:15</span>
                <span class="border border-dark col s1">17:30</span>
                <span class="border border-dark col s1">17:45</span>
                <span class="border border-dark col s1">18:00</span>
                <span class="border border-dark col s1">18:15</span>
                <span class="border border-dark col s1">18:30</span>
                <span class="border border-dark col s1">18:45</span>
                <span class="border border-dark col s1">19:00</span>
                <span class="border border-dark col s1">19:15</span>
                <span class="border border-dark col s1">19:30</span>
                <span class="border border-dark col s1">19:45</span>
                <span class="border border-dark col s1">20:00</span>
                <span class="border border-dark col s1">20:15</span>
                <span class="border border-dark col s1">20:30</span>
                <span class="border border-dark col s1">20:45</span>
            </div>
        </div>
    </div>
</div>

<br>

<!--Footer-->
<footer>
    <div class="footer">
        <div>
            <ul class="socials">
                <li>
                    <a href="http://facebook.com" target="_blank" rel="noopener"><i
                            class="fa-brands fa-facebook"></i></a>
                </li>
                <li>
                    <a href="http://twitter.com" target="_blank" rel="noopener"><i class="fa-brands fa-twitter"></i></a>
                </li>
                <li>
                    <a href="http://instagram.com" target="_blank" rel="noopener"><i
                            class="fa-brands fa-instagram"></i></a>
                </li>
                <li>
                    <a href="http://youtube.com" target="_blank" rel="noopener"><i class="fa-brands fa-youtube"></i></a>
                </li>
            </ul>
        </div>
    </div>
</footer>

{% endblock content %}

templates/manage_booking.html
{% extends 'base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-2 m-3 g-4">
    {% for reservation in reservations %}
    <div class="col-md-4 offset-md-4 col-sm-6 offset-sm-3">
        <div class="card manage border border-0 d-flex justify-content-center h-100 mx-2">
            <div class="card-body h-100 mx-2">
                <h4 class="text-center">
                    Booking Name: {{ reservation.name }}
                </h4>
                <div class="card-text">
                    <div class="align-self-center">
                        <p class="mb-2"><strong>Time:</strong>{{ reservation.time }}</p>
                        <p class="mb-2"><strong>Day:</strong> {{ reservation.day }}</p>
                        <p class="mb-2"><strong>Party Size:</strong> {{ reservation.party_size }}</p>
                    </div>
                    <a href="{% url 'update_booking' reservation.id %}" class="btn btn-success">Update</a>
                    <a href="{% url 'remove_booking' reservation.id %}" class="btn btn-danger"
                        data-bs-toggle="modal" data-bs-target="#deleteMessage">Remove</a>
                    <div class="modal fade" id="deleteMessage" tabindex="-1" aria-labelledby="deleteMessageLabel"
                        aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="deleteMessageLabel">Confirm Reservation Deletion</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Delete Reservation ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="mt-2 mb-3 btn btn-secondary"
                                        data-bs-dismiss="modal">Close</button>
                                    <a class="mt-2 mb-3 btn btn-secondary"
                                        href="{% url 'remove_booking' reservation.id %}">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

templates/update_reservation.html
{% extends "base.html" %} 
{% block content %}

<div class="container">
    <div class="card-content">
        <h2 class="mx-auto" style="width: 300px">Reservation Update</h2>
    </div>
</div>

<br>

<div class="container">
  <div class="row">
    <div class="col-s12-m4">      
        <div class="card">
          <form method="post">
            {% csrf_token %} {{ form.as_p }}

            <input  type="submit" value="Update" class="btn-small btn-success submit-button">
          </form>
        </div>      
    </div>
  </div>
</div>

{% endblock content %}